"""Unit tests for the batch methods and webhook verification. No network: HTTP is mocked."""

from __future__ import annotations

import json

import pytest
import responses

from getyoutubetranscript import Client, GetYouTubeTranscriptError, verify_webhook_signature

BASE_URL = "https://getyoutubetranscript.com/api/v1"
BATCH_ID = "324eb615-e4d5-4b3c-b8e7-04235671066b"


@pytest.fixture
def client() -> Client:
    return Client(api_key="sk_live_test_key")


def _batch(status: str = "completed", **extra):
    return {"success": True, "data": {"batch_id": BATCH_ID, "status": status, "total": 3, "pending": 0, **extra}}


@responses.activate
def test_get_transcript_languages_sends_video_param(client: Client):
    data = {"video_id": "kJQP7kiw5Fk", "default_language_code": "en",
            "languages": [{"language_code": "en", "name": "English", "caption_type": "manual"}]}
    responses.add(responses.GET, f"{BASE_URL}/transcript/languages", json={"success": True, "data": data}, status=200)

    assert client.get_transcript_languages("https://youtu.be/kJQP7kiw5Fk") == data
    assert responses.calls[0].request.url == f"{BASE_URL}/transcript/languages?v=https%3A%2F%2Fyoutu.be%2FkJQP7kiw5Fk"


@responses.activate
def test_create_batch_posts_json_body_and_idempotency_header(client: Client):
    responses.add(responses.POST, f"{BASE_URL}/batch", json=_batch("queued", webhook_secret="whsec_x"), status=202)

    result = client.create_batch(
        ["jNQXAC9IVRw", "https://youtu.be/dQw4w9WgXcQ"],
        language="es",
        timestamps=True,
        webhook_url="https://example.com/hook",
        idempotency_key="job-42",
    )

    assert result["batch_id"] == BATCH_ID
    request = responses.calls[0].request
    assert request.headers["Authorization"] == "Bearer sk_live_test_key"
    assert request.headers["Idempotency-Key"] == "job-42"
    assert json.loads(request.body) == {
        "videos": ["jNQXAC9IVRw", "https://youtu.be/dQw4w9WgXcQ"],
        "language": "es",
        "timestamps": True,
        "webhook_url": "https://example.com/hook",
    }


@responses.activate
def test_create_batch_omits_unset_options(client: Client):
    responses.add(responses.POST, f"{BASE_URL}/batch", json=_batch("queued"), status=202)
    client.create_batch(["jNQXAC9IVRw"])
    request = responses.calls[0].request
    assert json.loads(request.body) == {"videos": ["jNQXAC9IVRw"]}
    assert "Idempotency-Key" not in request.headers


def test_create_batch_requires_videos(client: Client):
    with pytest.raises(ValueError):
        client.create_batch([])


@responses.activate
def test_create_batch_surfaces_api_error_code(client: Client):
    responses.add(
        responses.POST,
        f"{BASE_URL}/batch",
        json={"success": False, "code": "TOO_MANY_BATCHES", "message": "You can have at most 5 unfinished batches."},
        status=429,
    )
    with pytest.raises(GetYouTubeTranscriptError) as excinfo:
        client.create_batch(["jNQXAC9IVRw"])
    assert excinfo.value.code == "TOO_MANY_BATCHES"
    assert excinfo.value.status_code == 429


@responses.activate
def test_get_batch_sends_id_offset_limit(client: Client):
    responses.add(responses.GET, f"{BASE_URL}/batch", json=_batch(items=[], next_offset=None), status=200)
    client.get_batch(BATCH_ID, offset=20, limit=10)
    assert responses.calls[0].request.url == f"{BASE_URL}/batch?id={BATCH_ID}&offset=20&limit=10"


@responses.activate
def test_wait_for_batch_polls_then_collects_every_page(client: Client, monkeypatch):
    monkeypatch.setattr("getyoutubetranscript.client.time.sleep", lambda _seconds: None)
    pages = [
        _batch("processing", pending=2, items=[], next_offset=1),
        _batch("completed", items=[{"position": 0}], next_offset=1),  # status check after polling
        _batch("completed", items=[{"position": 0}, {"position": 1}], next_offset=2),
        _batch("completed", items=[{"position": 2}], next_offset=None),
    ]
    for page in pages:
        responses.add(responses.GET, f"{BASE_URL}/batch", json=page, status=200)

    result = client.wait_for_batch(BATCH_ID, poll_interval=0, page_size=2)

    assert [item["position"] for item in result["items"]] == [0, 1, 2]
    assert result["next_offset"] is None
    assert len(responses.calls) == 4


@responses.activate
def test_wait_for_batch_times_out(client: Client):
    responses.add(responses.GET, f"{BASE_URL}/batch", json=_batch("processing", pending=3, items=[]), status=200)
    with pytest.raises(TimeoutError):
        client.wait_for_batch(BATCH_ID, poll_interval=0, timeout=0)


# Generated by the server's own signer (app/lib/batch/webhookDelivery.ts signWebhookBody),
# so this proves the SDK and the API agree byte for byte.
SERVER_BODY = (
    '{"event":"batch.completed","batch_id":"324eb615-e4d5-4b3c-b8e7-04235671066b",'
    '"status":"completed","total":3,"succeeded":2,"failed":1,"credits_charged":2}'
)
SERVER_HEADER = "t=1790000000,v1=ec02d3c715a86cce454f4403eadc3b44077ed4289b699f4333455dc789fa9a4f"
SECRET = "whsec_test_secret"


def test_verify_webhook_signature_accepts_server_signature():
    assert verify_webhook_signature(SERVER_BODY, SERVER_HEADER, SECRET, now=1790000000)
    assert verify_webhook_signature(SERVER_BODY.encode(), SERVER_HEADER, SECRET, now=1790000100)


@pytest.mark.parametrize(
    "body, header, secret, now",
    [
        (SERVER_BODY + " ", SERVER_HEADER, SECRET, 1790000000),  # body changed
        (SERVER_BODY, SERVER_HEADER, "whsec_other", 1790000000),  # wrong secret
        (SERVER_BODY, SERVER_HEADER, SECRET, 1790000000 + 301),  # too old
        (SERVER_BODY, SERVER_HEADER.replace("t=1790000000", "t=1790000001"), SECRET, 1790000000),  # timestamp swapped
        (SERVER_BODY, None, SECRET, 1790000000),
        (SERVER_BODY, "garbage", SECRET, 1790000000),
        (SERVER_BODY, SERVER_HEADER, "", 1790000000),
    ],
)
def test_verify_webhook_signature_rejects(body, header, secret, now):
    assert not verify_webhook_signature(body, header, secret, now=now)


def test_verify_webhook_signature_age_check_can_be_disabled():
    assert verify_webhook_signature(SERVER_BODY, SERVER_HEADER, SECRET, tolerance_seconds=0, now=0)
